require: rubocop-performance

AllCops:
  TargetRubyVersion: 2.7

Layout:
  Enabled: false

Metrics:
  Enabled: false

Style:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true
