require:
  - rubocop-minitest
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rake

# trying to be good  O:)
AllCops:
  TargetRubyVersion: 3.0.1
  NewCops: enable
  Exclude:
    - ___*/**/*           # '___' prefixed dirs are excluded
    - vendor/bundle/**/*  # avoid Error: RuboCop found unsupported Ruby version 2.1 in `TargetRubyVersion` parameter (in vendor/bundle/ruby/3.0.0/gems/rainbow-3.0.0/.rubocop.yml).

# No, thank you!
Layout:
  Enabled: false

# affect performance
Metrics:
  Enabled: false

# not cool
Style/CommentedKeyword:
  Enabled: false
Style/EmptyCaseCondition:
  Enabled: false
Style/Documentation:
  Enabled: false

# these cops are disabled only in the test files in order to
# allow to copy and paste the failed output for test reconciliation
Style/StringLiterals:
  Enabled: true
  Exclude:
  - test/**/*
Style/HashSyntax:
  Enabled: true
  Exclude:
  - test/**/*
Style/SymbolArray:
  Enabled: true
  Exclude:
  - test/**/*
