AllCops:
  TargetRubyVersion: 2.3

Layout:
  Enabled: false

Metrics:
  Enabled: false

Style:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  Enabled: false
