plugins:
  - rubocop-performance
  - rubocop-minitest
  - rubocop-rake
  - rubocop-packaging
  - rubocop-thread_safety

# trying to be good  O:)
AllCops:
  SuggestExtensions: false
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - ___*/**/*
    - "**/node_modules/**/*"
    - "gem/apps/enable_rails_page_segment.rb"
    - coverage/**/*
    - docs/**/*
    - src/**/*
    - vendor/**/*  # fix the problem with github ruby

Layout/LineLength:
  Max: 130
  Exclude:
  - test/**/*

Layout/BeginEndAlignment:
  EnforcedStyleAlignWith: begin

Layout/ExtraSpacing:
  AllowForAlignment:
    Enabled: true
  AllowBeforeTrailingComments:
    Enabled: true
  Exclude:
    - test/**/*
    - gem/bin/pagy

Layout/EmptyLines:
  Exclude:
    - gem/config/pagy.rb

Layout/BlockAlignment:
  Enabled: false

Layout/EndAlignment:
  EnforcedStyleAlignWith: keyword

Layout/HashAlignment:
  Enabled: false

Layout/ClosingParenthesisIndentation:
  Enabled: false

# bad for performance
Metrics:
  Enabled: false

Naming/VariableNumber:
  CheckSymbols: false

Naming/MethodParameterName:
  Enabled: false

# not cool
Style/CommentedKeyword:
  Enabled: false
Style/EmptyCaseCondition:
  Enabled: false
Style/LambdaCall:
  Enabled: false
Style/NumberedParametersLimit:
  Enabled: false

# Cannot inline the disabling in the file because rubocop complains anyway
Style/RedundantInitialize:
  Exclude:
    - test/mock_helpers/arel.rb

# Please!
Style/StringConcatenation:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
Style/Documentation:
  Enabled: false
# These cops are disabled only in the test files in order to
# allow to copy and paste the failed output for test reconciliation
Style/StringLiterals:
  Enabled: true
  Exclude:
  - test/**/*

Style/HashSyntax:
  Enabled: true
  Exclude:
    - test/**/*

Layout/SpaceAroundOperators:
  Enabled: true
  Exclude:
    - test/**/*

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true
  Exclude:
    - test/**/*

Lint/MissingSuper:
  Enabled: false

Minitest/EmptyLineBeforeAssertionMethods:
  Enabled: false
