AllCops:
  TargetRubyVersion: 2.2

Layout:
  Enabled: false

Metrics:
  Enabled: false

Style:
  Enabled: false

Gemspec/OrderedDependencies:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  Enabled: false
