[Container]

# The Project needs to test with chrome
Volume=shared_opt:/opt:z
Environment=PATH=/opt/bun/bin:/usr/local/bundle/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# Use a volume to store the node_modules dir
Volume=%N_node_modules:/%N/node_modules:z
