FROM debian:buster

# install required packages
RUN apt-get update && apt-get install --no-install-recommends -y locales \
 && sed -i 's/^# *\(en_US.UTF-8\)/\1/' /etc/locale.gen \
 && locale-gen \
 && apt-get install -y \
        curl git nano\
        libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb \
        libcanberra-gtk* \
 && rm -rf /var/lib/apt/lists/* \
 && apt-get clean

# create and setup user == to local user
#    - same pasword for user and root
#   - color prompt for user and root
ARG user
ARG group
ARG uid
ARG gid
ARG password=rubydev
ARG term=${term:-xterm-256color}
ENV TERM=$term

RUN groupadd --gid=$gid --force $group \
 && useradd --uid=$uid --gid=$gid --shell=/bin/bash --create-home $user \
 && echo $user:$password | chpasswd \
 && echo root:$password | chpasswd \
 && sed -i 's/#force_color_prompt=yes/force_color_prompt=yes/' /home/$user/.bashrc \
 && sed -i 's/\\u@\\h\\\[\\033\[00m\\\]:\\\[\\033\[01;34m\\\]\\w\\\[\\033\[00m\\\]/\\u \\\[\\033\[01;34m\\\]\\w\\\[\\033\[00m\\\] /' /home/$user/.bashrc \
 && echo "export PROMPT_COMMAND='history -a' && export HISTFILE=/home/$user/.bash_history" >> /home/$user/.bashrc \
 && cp /home/$user/.bashrc /root/.bashrc

VOLUME /home/$user

# install node in /opt
ARG node_version=v16.9.1
RUN mkdir /opt/node \
 && curl https://nodejs.org/dist/${node_version}/node-${node_version}-linux-x64.tar.xz \
        | tar xfJ - --strip-components 1 -C /opt/node
ENV PATH /opt/node/bin:${PATH}

RUN mkdir -p /pagy/test/e2e/node_modules \
 && touch /pagy/test/e2e/node_modules/.keep \
 && chown -R $uid:$gid /pagy/test/e2e/node_modules

USER $user

RUN mkdir \
        /home/$user/.config \
        /home/$user/.cache
