name: Code
description: File a bug report
labels: [ "bug" ]
title: 'Bug: '

body:
  - type: markdown
    attributes:
      value: |
        #### Thank you for your bug report!
        
        Please understand that...
        1. Code issues are reserved for real, REPRODUCIBLE code bugs
        2. We won't guess/install/setup/debug your problem out of some description/snippet/complete-application.

        _If you are not sure that your problem is actually a bug, or you have problems reproducing it, please ask for [support](https://github.com/ddnexus/pagy/discussions/categories/q-a) instead._

        #### Before posting, ensure to...

        1. Run Pagy version 43.3.1
        2. Search through [Docs](https://ddnexus.github.io/pagy/), [Issues](https://github.com/ddnexus/pagy/issues), and [Q&A](https://github.com/ddnexus/pagy/discussions/categories/q-a)
        3. Provide MINIMAL code to reproduce it. For example:
          - An edited single-file APP from the [Pagy Playground](https://ddnexus.github.io/pagy/sandbox/playground)
          - A plain ruby file that can run as a single command like `ruby my_issue.rb`

  - type: checkboxes
    id: support
    attributes:
      label: Disclaimer
      options:
        - label: I am aware that this issue will be closed or converted to a discussion if the requested code is missing or invalid.
          required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: Concisely describe what happens WITH THE CODE you provided and what should happen instead...
    validations:
      required: true
