name: Documentation
description: File a documentation issue
labels: [ "documentation" ]
title: 'Docs: '
assignees:
  - benkoshy

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this documentation issue!

        #### Before posting, ensure to...

        - Search through [Docs](https://ddnexus.github.io/pagy/), [Issues](https://github.com/ddnexus/pagy/issues), and [Q&A](https://github.com/ddnexus/pagy/discussions/categories/q-a)

  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: Please, describe the issue...
    validations:
      required: true
