# encoding: utf-8
# frozen_string_literal: true

require 'digest'

class Pagy

  # default :sizes nil will use {0 => :size}
  VARS[:sizes] = nil

  # The multiple series generated by the :sizes hash
  # If :sizes is nil it will use the single {0 => size}
  # Example:
  # >> pagy = Pagy.new(count:1000, page: 20, sizes: {0 => [1,2,2,1], 350 => [2,3,3,2], 550 => [3,4,4,3]})
  # >> pagy.multi_series
  # #=> { "0"   => [1, :gap, 18, 19, "20", 21, 22, :gap, 50],
  #       "350" => [1, 2, :gap, 17, 18, 19, "20", 21, 22, 23, :gap, 49, 50],
  #       "550" => [1, 2, 3, :gap, 16, 17, 18, 19, "20", 21, 22, 23, 24, :gap, 48, 49, 50] }
  def multi_series
    sizes = @vars[:sizes] || {0 => @vars[:size]}
    sizes.key?(0) or raise(ArgumentError, "expected :sizes to contain the 0 size; got #{sizes.inspect}")
    {}.tap {|multi_series| sizes.each {|width, size| multi_series[width.to_s] = series(size)}}
  end

  module Frontend

    if defined?(Oj)
      # returns a script tag with the JSON-serialized args generated with the faster oj gem
      def pagy_json_tag(*args)
        %(<script type="application/json" class="pagy-json">#{Oj.dump(args, mode: :strict)}</script>)
      end
    else                       # use slower standard json
      require 'json'
      # returns a script tag with the JSON-serialized args generated with the slower to_json
      def pagy_json_tag(*args)
        %(<script type="application/json" class="pagy-json">#{args.to_json}</script>)
      end
    end

    # returns the SHA1 (fastest on modern ruby) string used as default `id` attribute by all the `*_js` tags
    def pagy_id
      "pagy-#{Digest::SHA1.hexdigest(caller(2..2)[0].split(':in')[0])}"
    end

  end

end
