name: API Test

on:
  workflow_dispatch:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  skip_check:
    name: Skip Check
    continue-on-error: true
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          concurrent_skipping: 'never'
          skip_after_successful_duplicate: 'true'
          paths: '[
            ".github/workflows/api-test.yml",
            ".simplecov",
            ".rubocop",
            "gem/**",
            "Gemfile.lock",
            "test/unit/**",
            "tasks/**"
            ]'
          paths_ignore: '[
            "gem/config/**",
            "gem/locales/**",
            "!gem/locales/en.yml",
            "**/*.md"
            ]'
          do_not_skip: '["workflow_dispatch"]'

  api_test:
    needs: skip_check
    if: ${{ needs.skip_check.outputs.should_skip != 'true' }}
    name: API ${{ matrix.ruby-version }} Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.3', '3.4', '4.0']
      fail-fast: false
    steps:
      - uses: actions/checkout@v7
      - name: Set up ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Test Rubocop compliance
        run: bundle exec rubocop --format github
      - name: Test current and next API
        run: bundle exec thor test:api:all
      - name: Test API Coverage
        if: matrix.ruby-version == '4.0'
        run: bundle exec thor test:api:coverage # fail for coverage < 100%
