name: E2E Test

on:
  workflow_dispatch:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  skip_check:
    name: Skip Check
    continue-on-error: true
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5.3.1
        with:
          concurrent_skipping: 'never'
          skip_after_successful_duplicate: 'true'
          paths: '[
            ".github/workflows/e2e-test.yml",
            "gem/**",
            "test/e2e/**",
            "Gemfile.lock",
            "bun.lockb"
            ]'
          paths_ignore: '[
            "gem/config/**",
            "gem/locales/**",
            "!gem/locales/en.yml",
            "**/*.md"
            ]'
          do_not_skip: '["workflow_dispatch"]'

  e2e_test:
    needs: skip_check
    if: ${{ needs.skip_check.outputs.should_skip != 'true' }}
    name: E2E Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.1
      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1
      - name: Set up ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '4.0'
          bundler-cache: true
      - name: Run E2E Tests
        run: bundle exec rake test:e2e
