#!/bin/bash

# Ensure the commit message includes the prefix when it changes any file in the gem root path
# Used to automate the filtering of the commit messages in the CHANGELOG

set -e

prefix='[GEM] '

gem_changes=$(git diff --cached --name-status --relative=gem)
if [[ -n "$gem_changes" ]]
then
	msg=$(cat "$1")
	if [[ $msg != "$prefix"* ]]
	then
		echo "${prefix}${msg}" > "$1"
	fi
fi
